### ISSUE TITLE
Fonts are outlines, hard to read

### ISSUE THREAD

**Issue by ScottESanDiego** [Axeia/qBittorrentCompanion#1]
I really like where this project is going, as a refugee from `transmission-remote` :-)

Unfortunately, both the last release and the preview don't render properly for me on Win 11.  I get fonts that are outlines (more like I can only see the anti-aliasing)

Ideas?

![Screenshot 2024-08-11 101708](https://github.com/user-attachments/assets/f1ef2118-c381-4686-99f4-fc1a15577dac)

**Comment by Axeia** [comment]
Thank you for giving my project a go, I didn't expect anyone to use this just yet to be honest haha.
From the looks of it you're using "Light mode" rather than "Dark mode" which I hadn't tested at all yet and I think is leading to this odd font behaviour. I had already made several changes which I think resolved this issue to begin with but looking at this screenshot I figured the whole help section can do with a little bit of a revamp.

![image](https://github.com/user-attachments/assets/90bd912e-1715-4f3e-a188-fd90d0af582f)

It should look like the image above now :) in the latest publish version, let me know if it's resolved for you.

**Comment by ScottESanDiego** [comment]
Thanks for the fix.  Seems to look normal now.

I assume to change (e.g.,) the transparency of the torrent list it's editing the "Color Test" settings, but the weird font thing is gone from before.

**Comment by Axeia** [comment]
You can ignore the `Color test` section in settings. 
It's there so I can see how the colors interact. And so that I have a reference to the colors available to me by default in the UI framework that's used (Avalonia). Basically the pallet I use to paint the application with :)
